### ISSUE TITLE
Reconfiguring binds

### ISSUE THREAD

**Issue by sokayloc** [t5mat/turnbinds#1]
I love the look of this new update. Only problem is I don't know how to reconfigure the binds. R doesn't seem to work anymore and I don't know what values would change it in the .ini file.

**Comment by t5mat** [comment]
Hi, thanks! 🙂

I haven't had the chance to update the README yet. I'll close this issue once it's done. Sorry!

In the meantime, use the up/down arrow keys to navigate, and press ENTER to edit a bind (or variable).

**Comment by t5mat** [comment]
Done.
