### ISSUE TITLE
Turnbinds dont work

### ISSUE THREAD

**Issue by safetydog1** [t5mat/turnbinds#3]
No matter what i do the turnbinds wont work. Is there something i need to install to get them to work?

**Comment by t5mat** [comment]
There's nothing you need to install.

Some anti-cheat software are known to prevent the program from operating. I've added a section in the README that addresses anti-cheat software.

In short, use this without any anti-cheat software running in the background and it should work. If there's still a problem, feel free to open a new issue with a bit more info about your setup and what exactly doesn't work.
